#%RAML 0.8
title: Subway API
baseUri: http://{host}/rest/{version}
version: v1
baseUriParameters:
  host:
/import:
  displayName: importar dummy data 
  get:
    description: importa dummy data para poder probar los endpoints
    responses:
      200:
/pedidos:
  displayName: pedidos
  get:
    description: recupera lista de todos los pedidos realizados
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "id": "1",
                  "productoCantidad": 
                  {
                  	"p1": 1,
                  	"p2": 3
                  },
                  "sucursal": "s1",
                  "email": "cliente1@mail.com",
                  "promociones": [
                    "promo1",
                    "promo2"
                  ]
                },
                {
                  "id": "2",
                  "productoCantidad": 
                  {
                  	"p4": 2,
                  	"p5": 6
                  },
                  "sucursal": "s1",
                  "email": "cliente2@mail.com",
                  "promociones": [
                    "promo3"
                  ]
                }
              ]
  post:
    description: registra un pedido nuevo
    body:
      application/json:
        schema:  pedidoNuevo          
    responses:
      201:
        body:
          application/json:
            schema: pedidoRegistrado
              
schemas:
  - pedidoNuevo: |
      {
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "id": "http://jsonschema.net",
        "required": true,
        "properties": {
          "productoCantidad": {
            "type": "object",
            "patternProperties": {
              ".{1,}": { "type": "integer" }
            },
            "required": true
          },
          "email": {
            "type": "string",
            "required": true
          }
        }
      }
  - pedidoRegistrado: |
      {
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "id": "http://jsonschema.net",
        "required": true,
        "properties": {
          "id": {
            "type": "integer",
            "required": true
          },
          "productoCantidad": {
            "type": "object",
            "patternProperties": {
              ".{1,}": { "type": "integer" }
            },
            "required": true
          },
          "email": {
            "type": "string",
            "required": true
          },
          "sucursal": {
            "type": "string",
            "required": true
          },
          "promociones": {
            "type": "array",
            "minItems": 1,
            "items": { "type": "string" },
            "uniqueItems": true
          }
        }
      }
 